### ISSUE TITLE
sorting based on change type

### ISSUE THREAD

**Issue by dennis-wey** [pavelzw/pixi-diff-to-markdown#25]
Hi @pavelzw ,
I just tried the tool out and it's really great!

One thing I think could be useful would be to have different sorting options.

Right now it's sorted based on package name. I think it's a good default but it would be great to have the option to sort based on change type. So that all packages with a major version changes are on top.

**Comment by pavelzw** [comment]
It actually already is sorted by explicit/implicit, then change type and then name.

https://github.com/pavelzw/pixi-diff-to-markdown/blob/5492b73f339d94a991faf9fa0a5b537ad8ced200/pixi_diff_to_markdown/models.py#L77

Do you have an example where it's not the case?

**Comment by dennis-wey** [comment]
Oh you're right! I checked my example and I wasn't paying enough attention. I can confirm it's sorted the way you described it to be. Also I think the sorting makes the most sense and there is no need for an additional option here.

Thanks!
